### ISSUE TITLE
登录报错，无法使用

### ISSUE THREAD

**Issue by lichengxun** [void9main/SeeRedis#1]
运行环境：
linux：centos7
docker：19.03.2
docker-image：5.6.9-apache
Apache：2.4.10
PHP：5.6.9 (cli)
yum安装php5-redis
运行截图：
![image](https://user-images.githubusercontent.com/39191286/65324906-16038f00-dbe0-11e9-958e-b53c0a6068ed.png)
报错截图：
![image](https://user-images.githubusercontent.com/39191286/65324508-00419a00-dbdf-11e9-8aed-c57b46e4043f.png)
报错信息：
array_chunk() expects parameter 1 to be array, boolean given
`		$redis = Base::redis(0,$ip,$port);
        $info = $redis->info();
		$dbinfoNum = Base::getleft($ip,$port);
		$this->assign('dbNum',$dbinfoNum);
		$infoArr = array_chunk($info,"23",true);
		Session::set("redis_address",json_encode(array("ip"=>$ip,"port"=>$port),true));
		foreach($infoArr as $key=>$val){
        	$this->assign('dbInfo'.$key,$val);
		}
		$address = Session::get("redis_address");`
Call Stack
`1.in Content.php line 27`
`2.at Error::appError(2, 'array_chunk() expect...', '/var/www/html/SeeRed...', 27, ['ip' => '192.168.0.240', 'port' => '30003', 'redis' => object(Redis), ...])`
`3.at array_chunk(false, '23', true) in Content.php line 27`
`4.at Content->index()`
`5.at ReflectionMethod->invokeArgs(object(Content), []) in App.php line 343`
`6.at App::invokeMethod([object(Content), 'index'], []) in App.php line 611`
`7.at App::module(['index', 'content', 'index'], ['app_host' => '', 'app_debug' => true, 'app_trace' => false, ...], false) in App.php line 457`
`8.at App::exec(['type' => 'module', 'module' => ['index', 'content', 'index'], 'convert' => false], ['app_host' => '', 'app_debug' => true, 'app_trace' => false, ...]) in App.php line 139`
`9.at App::run() in start.php line 19`
`10.at require('/var/www/html/SeeRed...') in index.php line 17`

**Comment by lichengxun** [comment]
@void9main 项目还更新么？

**Comment by void9main** [comment]
你好，可能是因为缺少php.ini的redis扩展导致的，可以下载安装配置php_redis.so的扩展再试

**Comment by void9main** [comment]
项目将继续维护，目前正在考虑做一个脱离php语言和服务的桌面版管理器

**Comment by lichengxun** [comment]
![image](https://user-images.githubusercontent.com/39191286/65388529-4b92ae80-dd7f-11e9-9222-9f2fb2e005ec.png)
@void9main 这应该是装上了的把，是支持的redis版本太低么？

**Comment by void9main** [comment]
是的，建议使用高版本的扩展
![image](https://user-images.githubusercontent.com/13297338/65399869-a9f87500-ddf1-11e9-87dd-fe607a451f4c.png)

**Comment by lichengxun** [comment]
![image](https://user-images.githubusercontent.com/39191286/65435151-96c9c180-de52-11e9-9649-28bfe9f738a3.png)
@void9main seeRedis不支持密码么？

**Comment by void9main** [comment]
暂时不支持，后续可以考虑添加

**Comment by void9main** [comment]
这个本来就是给本地测试用的工具，一般测试不设密码
